BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Event] ADD [managerId] NVARCHAR(1000) NOT NULL CONSTRAINT [Event_managerId_df] DEFAULT '4916c73b-9235-4d62-a13a-bb050e1f2f1e';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
