### //login auth
POST http://localhost:4400/auth/login
Content-Type: application/json

{
    "email": "manager2.user",
    "password": "password"
}


###check details
GET http://localhost:4400/auth/checkDetails
Content-Type:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MDE3OWE5OC0zYTRjLTQzNGUtOWM5YS1mOWRiMmQ3ZjdiOTAiLCJlbWFpbCI6Im1hbmFnZXIyLnVzZXIiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTcyMTIwNjQ3MSwiZXhwIjoxNzIxMjEwMDcxfQ.M6k26YFP31mHlM9fzMjJJrW2n6oGqBENt3rGG3q7bIA