### //login auth
POST http://localhost:4400/auth/login
Content-Type: application/json

{
    "email": "marshcodes@gmail.com",
    "password": "password"
}


###check details
GET http://localhost:4400/auth/checkDetails
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmFiNjYwYS1iZmFhLTRmYjQtOTBmNi0yMzIyOTgxYTZmZDciLCJlbWFpbCI6Im1hcnNoY29kZXNAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MjE0ODkyOTEsImV4cCI6MTcyMTQ5Mjg5MX0.iBlfflLDO_NYkIUkFKt3I5eLmUnVzRK5GR2ttf5J0sw