### //login auth
POST http://localhost:4400/auth/login
Content-Type: application/json

{
    "email": "manager.user",
    "password": "password"
}


###check details
GET http://localhost:4400/auth/checkDetails
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWE1MjM5MC05OGU5LTQyNWItYmUwZS0xOTkyYzNkZDVjZWYiLCJlbWFpbCI6ImViMy41MjcyMS4yMUBzdHVkZW50LmNodWthLmFjLmtlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjE0NjQ4ODcsImV4cCI6MTcyMTQ2ODQ4N30.ekzIB3Zv1snRJkRBqCh_6FBYNNeSXCQV5y2EMU-jwJM