###new event
POST http://localhost:4400/event/createEvent
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNDc0MDYzLCJleHAiOjE3MjE0Nzc2NjN9.Ec3X2WmrCk7bwHY97_ehE0TEDFKc6KjTO_u4oqfz0SQ

{
  "name": "Pool Event",
  "managerId": "e756eeab-99c0-4779-ad15-4d1e97312a93",
  "description": "Pool ceremony",
  "moreInfo": "Come to managers meeting, message to admin organized by marshal",
  "location": "City Stadium",
  "date": "2024-10-03T00:00:00Z",  
 "time": "2024-10-03T19:00:00.000Z",
  "image": "http://example.com/image.jpg",
  "numberOfTickets": 100,
  "hasRegular": true,
  "regularPrice": 20.0,
  "hasVIP": false,
  "vipPrice": 50.0,
  "hasChildren": true,
  "childrenPrice": 10.0,
  "isPromoted": true,
  "promoDetails": "20% off for early birds!"
}

// The 'status' field indicates that the event is currently active. and can be set to iscanceled
// The 'nature' field suggests that the event might be pending approval or past event.

###get events   //admin
GET http://localhost:4400/event/getEvents
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDkzNzJlNi0yYTYzLTQzOWMtYTRmMy05NTA0Nzk2NmQzZjAiLCJlbWFpbCI6ImFkbWluLnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjE4ODE1NDMsImV4cCI6MTcyMTg4NTE0M30.WDiJtc__ZUageoXMxlDH0o7zvg5STSZPbxQD8TwmnNw


###get event by id
GET http://localhost:4400/event/getEvent/ef204698-c2e2-46c2-97c9-27fca73ab4a1


### events where nature is APPROVED and status ACTIVE(should dISPLAY THESE TO THE USER)
GET http://localhost:4400/event/getActiveEvents


###get events where nature is PENDING but are active //only admins
GET http://localhost:4400/event/getPendingEvents
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDkzNzJlNi0yYTYzLTQzOWMtYTRmMy05NTA0Nzk2NmQzZjAiLCJlbWFpbCI6ImFkbWluLnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjE4NTMwODcsImV4cCI6MTcyMTg1NjY4N30.2naaS7vEoPWijlkKK9yMlrrVdY-JGdT3X6to-8DsYFc

###get event by id(proably manager id)
GET http://localhost:4400/event/managerEvents/ef204698-c2e2-46c2-97c9-27fca73ab4a1


###get events by managerId 
GET http://localhost:4400/event/managerEvents/e756eeab-99c0-4779-ad15-4d1e97312a93
Content-Type:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNzI0MzI5LCJleHAiOjE3MjE3Mjc5Mjl9.4n-TWZa2nC2874RJhzq4_9lGE46eisoSR_qLSTCe0zY


###update event////manager pass eventId
PUT http://localhost:4400/event/updateEvent/d9c3c83a-5c76-43dc-b7fc-3733f68748d3
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MDE3OWE5OC0zYTRjLTQzNGUtOWM5YS1mOWRiMmQ3ZjdiOTAiLCJlbWFpbCI6Im1hbmFnZXIyQGdtYWlsLmNvbSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNzQ3NTE5LCJleHAiOjE3MjE3NTExMTl9.8Q6DBOnwCqCcmNx-gnn9NbwyrFPWl4gD0x3Sn4YpCtA

{
  "name": "Pool",
  "description": "An exciting music concert with various artists.",
  "moreInfo": "Join us for a night of fun and music!",
  "location": "City Stadium",
  "date": "2024-08-15T00:00:00Z",
  "time": "2024-08-15T19:00:00Z",
  "image": "http://example.com/image.jpg",
  "hasRegular": true,
  "regularPrice": 20.0,
  "hasVIP": true,
  "vipPrice": 50.0,
  "hasChildren": true,
  "childrenPrice": 10.0,
  "isPromoted": true,
  "promoDetails": "20% off for early birds!",
  "status": "ACTIVE",
  "nature": "PENDING",
  "discount": 10
}

###//cancel event  only manager
PUT http://localhost:4400/event/cancelEvent/d9c3c83a-5c76-43dc-b7fc-3733f68748d3
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDkzNzJlNi0yYTYzLTQzOWMtYTRmMy05NTA0Nzk2NmQzZjAiLCJlbWFpbCI6ImFkbWluLnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjE4ODE1NDMsImV4cCI6MTcyMTg4NTE0M30.WDiJtc__ZUageoXMxlDH0o7zvg5STSZPbxQD8TwmnNw



###  //approve event(Admin)
PUT http://localhost:4400/event/approveEvent/ef204698-c2e2-46c2-97c9-27fca73ab4a1
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDkzNzJlNi0yYTYzLTQzOWMtYTRmMy05NTA0Nzk2NmQzZjAiLCJlbWFpbCI6ImFkbWluLnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjE4ODI1NzAsImV4cCI6MTcyMTg4NjE3MH0.ftB2Sqp3FCXnYGdZU7EYrwl3ZjbR0rkv6cp7Fzfdo-c
                



#### //get aproved events  admin should see these eevnts also, mainly manager
GET http://localhost:4400/event/getApprovedEvents


### //add promotion to event (Event Manager)
PUT http://localhost:4400/event/addPromotion/e2e8ef6e-7a07-46fc-b412-ff9344353192
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNDczNjU0LCJleHAiOjE3MjE0NzcyNTR9.UHv4GT60jM3hAOo4INhDIG6esL-N3cMEO5g5vBBc4ow

{
  "isPromoted": true,
  "promoDetails": "free for all tickets"
}

### //remove promotion from event (Event Manager)
PUT http://localhost:4400/event/removePromotion/b5b7b129-20b9-460a-bb45-315af121d29c
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNDczNjU0LCJleHAiOjE3MjE0NzcyNTR9.UHv4GT60jM3hAOo4INhDIG6esL-N3cMEO5g5vBBc4ow



### reject event admin
PUT http://localhost:4400/event/rejectEvent/d9c3c83a-5c76-43dc-b7fc-3733f68748d3
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmFiNjYwYS1iZmFhLTRmYjQtOTBmNi0yMzIyOTgxYTZmZDciLCJlbWFpbCI6Im1hcnNoY29kZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIxMjA1MDAxLCJleHAiOjE3MjEyMDg2MDF9.rO8od2icGheqVQM6Ud2DmLqjxznyQr7J12dxJuuMAPs
                

###peaople artending a certain event
GET http://localhost:4400/event/getPeopleAttending/91243764-d90a-4bcc-92ae-8df95eb4ebb6           



### get total reservations in the system
GET http://localhost:4400/event/getTotalReservations
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDkzNzJlNi0yYTYzLTQzOWMtYTRmMy05NTA0Nzk2NmQzZjAiLCJlbWFpbCI6ImFkbWluLnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjEzODIyNTAsImV4cCI6MTcyMTM4NTg1MH0.epkAXCCxv1EuRE9-XS9fG-2-FWS3Wvx9z1_sYm8NOzI


### ///totalRSVPsManager/:id'   managers should see this for their stats
GET http://localhost:4400/event/totalRSVPsManager/90179a98-3a4c-434e-9c9a-f9db2d7f7b90
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MDE3OWE5OC0zYTRjLTQzNGUtOWM5YS1mOWRiMmQ3ZjdiOTAiLCJlbWFpbCI6Im1hbmFnZXIyLnVzZXIiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTcyMTYzOTE4NCwiZXhwIjoxNzIxNjQyNzg0fQ.Jq2cbhT9tFUYi6tuCGSJROMufOG5E4SYCWlP1Vhm3_s


### Get Event Count for all the  Managers
GET http://localhost:4400/event/managerEventCounts
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxNjM3Njg3LCJleHAiOjE3MjE2NDEyODd9.0yPSEQVdy5xtMf1ajSdQBYSvpzQTwNPaqIskiQnrqmE


### Get Event Count for a Specific Manager
GET http://localhost:4400/event/managerEventCount/90179a98-3a4c-434e-9c9a-f9db2d7f7b90