### //new reservation
POST http://localhost:4400/reservation/createReservation
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWE1MjM5MC05OGU5LTQyNWItYmUwZS0xOTkyYzNkZDVjZWYiLCJlbWFpbCI6ImViMy41MjcyMS4yMUBzdHVkZW50LmNodWthLmFjLmtlIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjE0Njg2MDYsImV4cCI6MTcyMTQ3MjIwNn0.__tEv8u4sXeSFh3dM5lHPQinQoMBdHMtkTCnWl0K9SE

{
  "eventId": "b5b7b129-20b9-460a-bb45-315af121d29c",
  "userId": "a5a52390-98e9-425b-be0e-1992c3dd5cef",
  "isRegular": true,
  "isVIP": false,
  "isChildren": false,
  "proxyName": "proxy",
  "numberOfPeople": 2,
  "createdAt": "2021-09-29T00:00:00.000Z",
  "updatedAt": "2021-09-29T00:00:00.000Z"
}

### //cancel reservation
PUT http://localhost:4400/reservation/cancelReservation/d9c3c83a-5c76-43dc-b7fc-3733f68748d3
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmFiNjYwYS1iZmFhLTRmYjQtOTBmNi0yMzIyOTgxYTZmZDciLCJlbWFpbCI6Im1hcnNoY29kZXNAZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MjEyMDYyOTYsImV4cCI6MTcyMTIwOTg5Nn0.hPeY4Wm3DI2lOtz4QrzMwWbZ8kD3ua45GdWt0AgQNK0



### //get all reservations
GET http://localhost:4400/reservation/getAllReservations
Content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxMTQ3MDQ0LCJleHAiOjE3MjExNTA2NDR9.Ejuepm7fvnMAsCQewEA6eeql5DdzAqzEEfdkm9itAmc

### //get reservation by id
GET http://localhost:4400/reservation/getOneReservation/0e6d2bd8-dac5-4ae4-8e59-35c945a49866
Content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmFiNjYwYS1iZmFhLTRmYjQtOTBmNi0yMzIyOTgxYTZmZDciLCJlbWFpbCI6Im1hcnNoY29kZXNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjEzMjI3OTksImV4cCI6MTcyMTMyNjM5OX0.gcmfXIXcFfmR-mEpLH39KfEKyj4bUIecurHemBjFN4w


### //calculate price
POST http://localhost:4400/reservation//calculatePrice


### //get sum of paid amounts for reservations based on event  and manager provide eventid
GET http://localhost:4400/reservation/getSumOfPaidAmounts/91243764-d90a-4bcc-92ae-8df95eb4ebb6&
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxMTQ5NDczLCJleHAiOjE3MjExNTMwNzN9.849TBWzks2FVag9onGidiJlFcTOGCSJFJvcMcuJyo7A


### //get total paid amount for all events
GET http://localhost:4400/reservation/getTotalPaidAmountForAllEvents
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzU2ZWVhYi05OWMwLTQ3NzktYWQxNS00ZDFlOTczMTJhOTMiLCJlbWFpbCI6Im1hbmFnZXIudXNlciIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzIxMTQ5NDczLCJleHAiOjE3MjExNTMwNzN9.849TBWzks2FVag9onGidiJlFcTOGCSJFJvcMcuJyo7A

