### //new reservation
POST http://localhost:4400/reservation/createReservation
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZGIxM2QzYS1iMTQ4LTRmYzMtYTE3ZS1iZDgwZWRiYjlkOWEiLCJlbWFpbCI6InVzZXIudXNlciIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIxMTE5NzgxLCJleHAiOjE3MjExMjMzODF9.SNo9ArjVrZhLZ06KrUDEoAU5X3GAD8oqx8FQO3ueaNI

{
  "eventId": "91243764-d90a-4bcc-92ae-8df95eb4ebb6",
  "userId": "8b5a5b1d-e523-44c8-abb9-6c854898ac79",
  "isRegular": true,
  "isVIP": false,
  "isChildren": false,
  "proxyName": "proxy",
  "numberOfPeople": 10,
  "createdAt": "2021-09-29T00:00:00.000Z",
  "updatedAt": "2021-09-29T00:00:00.000Z"
}

### //cancel reservation
PUT http://localhost:4400/reservation/cancelReservation/2339df33-4f3b-4f49-8484-a9dc1506eec2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OGFmMDQzMi05NDk2LTRiOWMtYmQ1ZC0wYjI4MTNlZDNlYWIiLCJlbWFpbCI6ImpvaG55QG1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjEwNDgxODYsImV4cCI6MTcyMTA1MTc4Nn0.HHtBim-jTDbcMMv9aao3qcGAJIex0mLOKOymlmoq-Bo



### //get all reservations
GET http://localhost:4400/reservation/getAllReservations
Content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNDk4MDc1MC0wOTA2LTQyNmMtODA2MS1kOTk2OWMwMzMyZmUiLCJlbWFpbCI6InVzZXIuYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjEwNTI0MzIsImV4cCI6MTcyMTA1NjAzMn0.GQxbzdTjEO9h9OJ9jHBUDsLZ2JMcsN8qJKuMGFhp0bU

### //get reservation by id
GET http://localhost:4400/reservation/getOneReservation/60700aad-6257-466c-8043-dd1d33440023
Content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNDk4MDc1MC0wOTA2LTQyNmMtODA2MS1kOTk2OWMwMzMyZmUiLCJlbWFpbCI6InVzZXIuYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjEwNTI0MzIsImV4cCI6MTcyMTA1NjAzMn0.GQxbzdTjEO9h9OJ9jHBUDsLZ2JMcsN8qJKuMGFhp0bU
