BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Event] ALTER COLUMN [moreInfo] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [date] DATETIME2 NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [time] DATETIME2 NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [updatedAt] DATETIME2 NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [childrenPrice] FLOAT(53) NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [regularPrice] FLOAT(53) NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [vipPrice] FLOAT(53) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
